const FIREBASE_ACTIVO=false;
const firebaseConfig={apiKey:"PEGA_AQUI_TU_API_KEY",authDomain:"PEGA_AQUI.firebaseapp.com",projectId:"PEGA_AQUI_TU_PROJECT_ID",storageBucket:"PEGA_AQUI.appspot.com",messagingSenderId:"PEGA_AQUI",appId:"PEGA_AQUI"};
const ALBUM_ID="album-fifa-2026-javier",STORAGE_KEY="album-fifa-2026-progreso",UI_SCALE_KEY="album-fifa-2026-ui-scale",STICKER_DATA_KEY="album-fifa-2026-sticker-data",MOVEMENT_LOG_KEY="album-fifa-2026-movimientos";
const album=[
{id:"A",title:"Grupo A",type:"team",countries:[{key:"México",display:"México",code:"MEX"},{key:"Sudáfrica",display:"Sudáfrica",code:"RSA"},{key:"Corea del Sur",display:"Corea del Sur",code:"KOR"},{key:"Chequia",display:"República Checa",code:"CZE"}]},
{id:"B",title:"Grupo B",type:"team",countries:[{key:"Canadá",display:"Canadá",code:"CAN"},{key:"Bosnia y Herzegovina",display:"Bosnia y Herzegovina",code:"BIH"},{key:"Qatar",display:"Catar",code:"QAT"},{key:"Suiza",display:"Suiza",code:"SUI"}]},
{id:"C",title:"Grupo C",type:"team",countries:[{key:"Brasil",display:"Brasil",code:"BRA"},{key:"Marruecos",display:"Marruecos",code:"MAR"},{key:"Haití",display:"Haití",code:"HAI"},{key:"Escocia",display:"Escocia",code:"SCO"}]},
{id:"D",title:"Grupo D",type:"team",countries:[{key:"Estados Unidos",display:"Estados Unidos",code:"USA"},{key:"Paraguay",display:"Paraguay",code:"PAR"},{key:"Australia",display:"Australia",code:"AUS"},{key:"Turquía",display:"Turquía",code:"TUR"}]},
{id:"E",title:"Grupo E",type:"team",countries:[{key:"Alemania",display:"Alemania",code:"GER"},{key:"Curazao",display:"Curazao",code:"CUW"},{key:"Costa de Marfil",display:"Costa de Marfil",code:"CIV"},{key:"Ecuador",display:"Ecuador",code:"ECU"}]},
{id:"F",title:"Grupo F",type:"team",countries:[{key:"Países Bajos",display:"Países Bajos",code:"NED"},{key:"Japón",display:"Japón",code:"JPN"},{key:"Suecia",display:"Suecia",code:"SWE"},{key:"Túnez",display:"Túnez",code:"TUN"}]},
{id:"G",title:"Grupo G",type:"team",countries:[{key:"Bélgica",display:"Bélgica",code:"BEL"},{key:"Egipto",display:"Egipto",code:"EGY"},{key:"Irán",display:"Irán",code:"IRN"},{key:"Nueva Zelanda",display:"Nueva Zelanda",code:"NZL"}]},
{id:"H",title:"Grupo H",type:"team",countries:[{key:"España",display:"España",code:"ESP"},{key:"Cabo Verde",display:"Cabo Verde",code:"CPV"},{key:"Arabia Saudita",display:"Arabia Saudita",code:"KSA"},{key:"Uruguay",display:"Uruguay",code:"URU"}]},
{id:"I",title:"Grupo I",type:"team",countries:[{key:"Francia",display:"Francia",code:"FRA"},{key:"Senegal",display:"Senegal",code:"SEN"},{key:"Irak",display:"Irak",code:"IRQ"},{key:"Noruega",display:"Noruega",code:"NOR"}]},
{id:"J",title:"Grupo J",type:"team",countries:[{key:"Argentina",display:"Argentina",code:"ARG"},{key:"Argelia",display:"Argelia",code:"ALG"},{key:"Austria",display:"Austria",code:"AUT"},{key:"Jordania",display:"Jordania",code:"JOR"}]},
{id:"K",title:"Grupo K",type:"team",countries:[{key:"Portugal",display:"Portugal",code:"POR"},{key:"RD Congo",display:"Congo RD",code:"COD"},{key:"Uzbekistán",display:"Uzbekistán",code:"UZB"},{key:"Colombia",display:"Colombia",code:"COL"}]},
{id:"L",title:"Grupo L",type:"team",countries:[{key:"Inglaterra",display:"Inglaterra",code:"ENG"},{key:"Croacia",display:"Croacia",code:"CRO"},{key:"Ghana",display:"Ghana",code:"GHA"},{key:"Panamá",display:"Panamá",code:"PAN"}]},
{id:"FWC",title:"FWC",type:"fwc",countries:[{key:"FWC",display:"FWC",code:"FWC"}]},{id:"CC",title:"Coca-Cola",type:"cc",countries:[{key:"Coca-Cola",display:"Coca-Cola Latinoamérica / Chile",code:"CC"}]}];
const IS_BROWSER=typeof window!=="undefined"&&typeof document!=="undefined";
let state=loadLocalState(),movementLog=loadMovementLog(),stickerData=loadLocalStickerData(),activeTab="A",activeActionKey=null,uiScale=loadUiScale(),docRef=null,firebaseReady=false,saving=false,officialDataLoaded=false,pdfLibrariesLoading=null;const $=s=>document.querySelector(s);
if(IS_BROWSER)Object.assign(window,{changeTab,openCardActions,applyCardAction,closeCardModal,markVisibleAsOwned,clearVisibleTab,resetAlbum,exportData,openImportData,importDataFromFile,scrollToSection,toggleUiScaleMenu,changeUiScale,resetUiScale,exportMissingPdf,exportDuplicatesPdf});
function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function normalizeEntry(v){if(v==="owned")return{owned:true,duplicates:0};if(v==="duplicate")return{owned:true,duplicates:1};if(v&&typeof v==="object"&&!Array.isArray(v)){const owned=v.owned===true||v.status==="owned"||v.status==="duplicate";const duplicates=Math.max(0,Math.floor(Number(v.duplicates??v.duplicateCount??(v.status==="duplicate"?1:0))||0));if(owned)return{owned:true,duplicates}}return null}
function migrateState(raw){const m={};if(!raw||typeof raw!=="object"||Array.isArray(raw))return m;Object.entries(raw).forEach(([k,v])=>{const n=normalizeEntry(v);if(n)m[k]=n});return m}
function formatDateTimeParts(date=new Date()){const d=date instanceof Date?date:new Date(date);const pad=n=>String(n).padStart(2,"0");return{date:`${pad(d.getDate())}/${pad(d.getMonth()+1)}/${d.getFullYear()}`,time:`${pad(d.getHours())}:${pad(d.getMinutes())}`}}
function movementText(type,sticker){const detail=`${sticker.name} (${sticker.country}; ${sticker.code}; ${sticker.number})`,bulkDetail=`${sticker.country}; ${sticker.number} láminas actualizadas`;return{found:`Se encontró lámina ${detail}`,foundExchange:`Se obtuvo por intercambio lámina ${detail}`,duplicateAdded:`Se agregó repetida de lámina ${detail}`,duplicateExchanged:`Se intercambió lámina ${detail}`,markedMissing:`Se marcó como faltante lámina ${detail}`,bulkFound:`Se marcó grupo visible como encontrado (${bulkDetail})`,bulkCleared:`Se limpió grupo visible (${bulkDetail})`}[type]||`Se actualizó lámina ${detail}`}
function createMovementEntry(type,sticker,createdAt=new Date()){const stamp=createdAt instanceof Date?createdAt:new Date(createdAt),parts=formatDateTimeParts(stamp),safeSticker={name:sticker?.name||"Nombre no cargado",country:sticker?.country||"",code:sticker?.code||"",number:sticker?.number||""};return{id:`${stamp.getTime()}-${Math.random().toString(36).slice(2,8)}`,type,createdAt:stamp.toISOString(),date:parts.date,time:parts.time,text:movementText(type,safeSticker),sticker:safeSticker}}
function getDashboardMetrics(cards,total){let owned=0,duplicates=0;Object.values(cards||{}).forEach(e=>{if(e?.owned)owned++;duplicates+=Number(e?.duplicates)||0});const safeTotal=Math.max(0,Number(total)||0),missing=Math.max(0,safeTotal-owned),progress=safeTotal?Math.round(owned/safeTotal*100):0;return{owned,total:safeTotal,missing,duplicates,progress,foundLabel:`${owned}/${safeTotal}`}}
function loadLocalState(){try{return migrateState(JSON.parse(localStorage.getItem(STORAGE_KEY))||{})}catch{return{}}}
function loadMovementLog(){try{const raw=JSON.parse(localStorage.getItem(MOVEMENT_LOG_KEY))||[];return Array.isArray(raw)?raw.filter(i=>i&&typeof i==="object").slice(0,200):[]}catch{return[]}}
function saveLocalState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));$("#lastUpdateText").textContent="Último guardado local: "+new Date().toLocaleString("es-CL")}
function saveMovementLog(){try{localStorage.setItem(MOVEMENT_LOG_KEY,JSON.stringify(movementLog.slice(0,200)))}catch(e){console.warn("No se pudo guardar el registro de movimientos",e)}}
function getEntry(k){return state[k]||{owned:false,duplicates:0}}
function setSyncStatus(t,m=""){const e=$("#syncStatus");e.textContent=t;e.className=`badge ${m}`.trim()}
async function initFirebase(){if(!FIREBASE_ACTIVO){setSyncStatus("Guardado local activo","offline");return}try{const{initializeApp}=await import("https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js");const{getFirestore,doc,onSnapshot,setDoc,serverTimestamp}=await import("https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js");const app=initializeApp(firebaseConfig),db=getFirestore(app);docRef=doc(db,"albums",ALBUM_ID);firebaseReady=true;window.firebaseSetDoc=setDoc;window.firebaseServerTimestamp=serverTimestamp;setSyncStatus("Sincronización online activa","online");onSnapshot(docRef,s=>{if(!s.exists())return;const d=s.data();if(d?.cards){state=migrateState(d.cards);saveLocalState();render()}if(d?.updatedAt?.toDate)$("#lastUpdateText").textContent="Última actualización online: "+d.updatedAt.toDate().toLocaleString("es-CL")})}catch(e){console.error(e);setSyncStatus("Error al conectar Firebase","offline")}}
async function saveCloudState(){saveLocalState();if(!firebaseReady||!docRef||saving)return;saving=true;try{await window.firebaseSetDoc(docRef,{cards:state,updatedAt:window.firebaseServerTimestamp()},{merge:true})}catch(e){console.error(e);setSyncStatus("Error al guardar online","offline")}finally{saving=false}}
function getCardDefs(s){if(s.type==="team")return Array.from({length:20},(_,i)=>({stateNumber:String(i+1).padStart(2,"0"),displayNumber:String(i+1).padStart(2,"0"),dataNumber:String(i+1)}));if(s.type==="fwc")return[{stateNumber:"FWC 00",displayNumber:"00",dataNumber:"00"},...Array.from({length:19},(_,i)=>({stateNumber:`FWC ${i+1}`,displayNumber:`FWC-${i+1}`,dataNumber:`FWC-${i+1}`}))];return Array.from({length:14},(_,i)=>({stateNumber:`CC-${i+1}`,displayNumber:`CC-${i+1}`,dataNumber:`CC-${i+1}`}))}
function cardKey(s,c,n){return`${s}|${c}|${n}`}function totalCards(){return album.reduce((sum,s)=>sum+s.countries.length*getCardDefs(s).length,0)}function findSection(id){return album.find(s=>s.id===id)}function findCardContext(key){const[sectionId,countryKey,stateNumber]=key.split("|");const section=findSection(sectionId),country=section?.countries.find(i=>i.key===countryKey),card=section?getCardDefs(section).find(i=>i.stateNumber===stateNumber):null;return{section,country,card}}
function getMeta(section,country,card){let meta=null;if(section?.type==="team")meta=stickerData.teams?.[country.code]?.[card.dataNumber];if(section?.type==="fwc")meta=stickerData.fwc?.[card.dataNumber];if(section?.type==="cc")meta=stickerData.cc?.[card.dataNumber];return{country:meta?.country||country?.display||"",code:meta?.code||country?.code||section?.id||"",number:meta?.number||card?.displayNumber||"",name:meta?.name||"Nombre no cargado"}}
function allCardKeys(){const keys=[];album.forEach(s=>s.countries.forEach(c=>getCardDefs(s).forEach(card=>keys.push(cardKey(s.id,c.key,card.stateNumber)))));return keys}
function movementSticker(meta){return{name:meta.name,country:meta.country,code:meta.code,number:meta.number}}
function recordMovement(type,meta){const entry=createMovementEntry(type,movementSticker(meta));movementLog=[entry,...movementLog].slice(0,200);saveMovementLog();renderMovementLog()}
function statusText(e){if(!e.owned)return"Faltante";if(e.duplicates>0)return`Repetidas: ${e.duplicates}`;return"Encontrada"}function statusClass(e){if(!e.owned)return"";return e.duplicates>0?"duplicate":"owned"}
function renderTabs(){$("#tabs").innerHTML=album.map(s=>`<button class="tab-btn ${s.id===activeTab?"active":""}" onclick="changeTab('${s.id}')">${esc(s.id)}</button>`).join("")}
function changeTab(id){activeTab=id;renderTabs();renderContent()}
function renderContent(){const s=findSection(activeTab),cards=getCardDefs(s);$("#content").innerHTML=`<h2 class="group-title">${esc(s.title)}</h2><div class="countries">${s.countries.map(country=>`<article class="country"><h3>${esc(country.display)} <small>${esc(country.code)} · ${cards.length} láminas</small></h3><div class="cards-grid">${cards.map(card=>{const key=cardKey(s.id,country.key,card.stateNumber),entry=getEntry(key),meta=getMeta(s,country,card);return`<button class="card-btn ${statusClass(entry)}" data-key="${esc(key)}"><span class="sticker-number">${esc(meta.code)} ${esc(meta.number)}</span><span class="sticker-name">${esc(meta.name)}</span><span class="sticker-status">${esc(statusText(entry))}</span></button>`}).join("")}</div></article>`).join("")}</div>`;document.querySelectorAll(".card-btn[data-key]").forEach(b=>b.addEventListener("click",()=>openCardActions(b.dataset.key)))}
function updateStats(){const validState={};allCardKeys().forEach(k=>{if(state[k])validState[k]=state[k]});const metrics=getDashboardMetrics(validState,totalCards());$("#progressText").textContent=`${metrics.progress}%`;$("#foundText").textContent=metrics.foundLabel;$("#duplicateText").textContent=metrics.duplicates;$("#progressBar").style.width=`${metrics.progress}%`;$(".progress-wrap")?.setAttribute("aria-valuenow",String(metrics.progress))}
function getAllCollections(groupId=""){return album.filter(s=>!groupId||s.id===groupId).flatMap(section=>section.countries.map(country=>({id:`${section.id}|${country.key}`,section,country})))}
function renderGroupOptions(id,val){const s=document.getElementById(id);s.innerHTML=[`<option value="">Todos los grupos</option>`,...album.map(x=>`<option value="${esc(x.id)}">${esc(x.title)}</option>`)].join("");s.value=val||""}
function renderCountryOptions(id,g,val){const s=document.getElementById(id),cols=getAllCollections(g);s.innerHTML=[`<option value="">Todos los países/secciones</option>`,...cols.map(i=>`<option value="${esc(i.id)}">${esc(i.country.display)}</option>`)].join("");s.value=cols.some(i=>i.id===val)?val:""}
function setupFilterListeners(){["missing","duplicate"].forEach(t=>{const g=document.getElementById(`${t}Group`),c=document.getElementById(`${t}Country`);g.addEventListener("change",()=>{renderCountryOptions(`${t}Country`,g.value,"");renderFilterResult(t)});c.addEventListener("change",()=>renderFilterResult(t))})}
function renderFilterControls(){["missing","duplicate"].forEach(t=>{const g=document.getElementById(`${t}Group`),c=document.getElementById(`${t}Country`);renderGroupOptions(`${t}Group`,g.value||"");renderCountryOptions(`${t}Country`,g.value||"",c.value||"")})}
function getRowsForCollection(collection,type){return getCardDefs(collection.section).filter(card=>{const e=getEntry(cardKey(collection.section.id,collection.country.key,card.stateNumber));return type==="missing"?!e.owned:e.duplicates>0}).map(card=>{const key=cardKey(collection.section.id,collection.country.key,card.stateNumber);return{key,card,entry:getEntry(key),meta:getMeta(collection.section,collection.country,card)}})}
function renderFilterResult(type){const groupId=document.getElementById(`${type}Group`).value||"",countryId=document.getElementById(`${type}Country`).value||"",result=document.getElementById(`${type}Result`),label=type==="missing"?"faltantes":"repetidas";const cols=countryId?getAllCollections().filter(i=>i.id===countryId):getAllCollections(groupId);const total=cols.reduce((sum,c)=>sum+getRowsForCollection(c,type).length,0),showEmpty=Boolean(groupId||countryId);const content=cols.map(c=>{const rows=getRowsForCollection(c,type);if(!showEmpty&&rows.length===0)return"";return`<section class="filter-country-block"><div class="filter-country-title"><strong>${esc(c.country.display)}</strong><span>${esc(c.section.title)} · ${rows.length} ${label}</span></div>${rows.length?`<div class="card-list">${rows.map(r=>`<button class="mini-card ${type==="duplicate"?"duplicate":""}" onclick="openCardActions('${esc(r.key)}')">${esc(r.meta.code)} ${esc(r.meta.number)} · ${esc(r.meta.name)}${type==="duplicate"?` x${r.entry.duplicates}`:""}</button>`).join("")}</div>`:`<p class="filter-empty">Sin cartas ${label} en esta sección.</p>`}</section>`}).join("");result.innerHTML=`<div class="filter-summary"><strong>${total}</strong> carta(s) ${label} según el filtro aplicado.</div>${content||`<p class="filter-empty">No hay cartas ${label} para mostrar.</p>`}`}
function renderFilters(){renderFilterControls();renderFilterResult("missing");renderFilterResult("duplicate")}
function renderMovementLog(){const list=$("#movementList");if(!list)return;if(!movementLog.length){list.innerHTML=`<p class="movement-empty">Aún no hay movimientos registrados.</p>`;return}list.innerHTML=movementLog.slice(0,80).map(item=>{const parts=item.date&&item.time?{date:item.date,time:item.time}:formatDateTimeParts(item.createdAt);const s=item.sticker||{};return`<article class="movement-item"><div class="movement-time"><strong>${esc(parts.date)}</strong><span>${esc(parts.time)}</span></div><div class="movement-body"><p>${esc(item.text||"Movimiento registrado")}</p><div class="movement-meta"><span>${esc(s.country||"Sin país/sección")}</span><span>${esc(s.code||"")}</span><span>${esc(s.number||"")}</span></div></div></article>`}).join("")}
function openCardActions(key){activeActionKey=key;const{section,country,card}=findCardContext(key),meta=getMeta(section,country,card),entry=getEntry(key);$("#modalTitle").textContent=`${meta.code} ${meta.number}`;$("#modalDetail").innerHTML=`<strong>${esc(meta.name)}</strong><br>${esc(meta.country)} · Estado: <strong>${esc(statusText(entry))}</strong>`;const acts=[];if(!entry.owned){acts.push(["found","Marcar como encontrada","safe"]);acts.push(["foundExchange","Marcar como encontrada (Intercambio)","safe"])}else{if(entry.duplicates>0)acts.push(["exchange","Intercambiar","safe"]);acts.push(["addDuplicate","Agregar +1 repetida",""]);acts.push(["missing","Marcar como faltante","danger"])}$("#modalActions").innerHTML=acts.map(([a,t,c])=>`<button class="action-btn ${c}" onclick="applyCardAction('${a}')">${t}</button>`).join("");$("#cardModal").hidden=false}
function closeCardModal(){activeActionKey=null;$("#cardModal").hidden=true}
function applyCardAction(action){if(!activeActionKey)return;const ctx=findCardContext(activeActionKey),meta=getMeta(ctx.section,ctx.country,ctx.card),entry=getEntry(activeActionKey);const msg={found:`¿Marcar ${meta.code} ${meta.number} - ${meta.name} como encontrada?`,foundExchange:`¿Marcar ${meta.code} ${meta.number} - ${meta.name} como encontrada por intercambio?`,addDuplicate:`¿Agregar +1 repetida a ${meta.code} ${meta.number} - ${meta.name}?`,exchange:`¿Intercambiar una repetida de ${meta.code} ${meta.number} - ${meta.name}?`,missing:`¿Marcar ${meta.code} ${meta.number} - ${meta.name} como faltante?`};if(!confirm(msg[action]||"¿Confirmar acción?"))return;if(action==="found"||action==="foundExchange"){state[activeActionKey]={owned:true,duplicates:0};recordMovement(action,meta)}if(action==="addDuplicate"){state[activeActionKey]={owned:true,duplicates:(entry.duplicates||0)+1};recordMovement("duplicateAdded",meta)}if(action==="exchange"){state[activeActionKey]={owned:true,duplicates:Math.max(0,(entry.duplicates||0)-1)};recordMovement("duplicateExchanged",meta)}if(action==="missing"){delete state[activeActionKey];recordMovement("markedMissing",meta)}closeCardModal();saveCloudState();render()}
function visibleKeys(){const s=findSection(activeTab),cards=getCardDefs(s),keys=[];s.countries.forEach(c=>cards.forEach(card=>keys.push(cardKey(s.id,c.key,card.stateNumber))));return keys}
function markVisibleAsOwned(){if(!confirm("¿Marcar todas las láminas faltantes del grupo visible como encontradas?"))return;let updated=0;visibleKeys().forEach(k=>{const e=getEntry(k);if(!e.owned){state[k]={owned:true,duplicates:0};updated++}});if(updated)recordMovement("bulkFound",{name:findSection(activeTab)?.title||activeTab,country:findSection(activeTab)?.title||activeTab,code:activeTab,number:String(updated)});saveCloudState();render()}
function clearVisibleTab(){if(!confirm("¿Limpiar solo el grupo visible?"))return;let updated=0;visibleKeys().forEach(k=>{if(state[k])updated++;delete state[k]});if(updated)recordMovement("bulkCleared",{name:findSection(activeTab)?.title||activeTab,country:findSection(activeTab)?.title||activeTab,code:activeTab,number:String(updated)});saveCloudState();render()}
function resetAlbum(){if(!confirm("¿Reiniciar todo el álbum? Esta acción borrará el progreso local y el registro de movimientos de este navegador."))return;state={};movementLog=[];saveMovementLog();saveCloudState();render()}
function exportData(){const data={app:"album-fifa-2026",version:8,exportedAt:new Date().toISOString(),storageKey:STORAGE_KEY,movementLogKey:MOVEMENT_LOG_KEY,albumId:ALBUM_ID,cards:state,movements:movementLog};const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`album-fifa-2026-data-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);alert("Data exportada. Guarda el archivo JSON como respaldo.")}
function openImportData(){$("#dataImportInput").value="";$("#dataImportInput").click()}
function importDataFromFile(event){const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result),imported=migrateState(data.cards||data),total=Object.keys(imported).length;if(!confirm(`Se importarán ${total} láminas marcadas. Esto reemplazará la data actual y el registro de movimientos de este navegador. ¿Continuar?`))return;state=imported;movementLog=Array.isArray(data.movements)?data.movements.filter(i=>i&&typeof i==="object").slice(0,200):[];saveMovementLog();saveCloudState();render();alert("Data importada correctamente.")}catch(e){console.error(e);alert("No se pudo leer el archivo. Verifica que sea un JSON exportado desde esta página.")}};reader.readAsText(file)}
function loadLocalStickerData(){try{return JSON.parse(localStorage.getItem(STICKER_DATA_KEY))||{teams:{},fwc:{},cc:{}}}catch{return{teams:{},fwc:{},cc:{}}}}
function saveStickerData(){localStorage.setItem(STICKER_DATA_KEY,JSON.stringify(stickerData));updateOfficialStatus()}
function countStickerRows(){return Object.values(stickerData.teams||{}).reduce((sum,t)=>sum+Object.keys(t).length,0)+Object.keys(stickerData.fwc||{}).length+Object.keys(stickerData.cc||{}).length}
function updateOfficialStatus(){const total=countStickerRows();$("#officialDataStatus").textContent=total?`Base oficial cargada: ${total} láminas con nombre.`:"Cargando base oficial de láminas..."}
function parseStickerText(text){const data={teams:{},fwc:{},cc:{}};let section="teams";text.split(/\r?\n/).map(l=>l.trim().replace(/^\uFEFF/,"")).filter(Boolean).forEach(line=>{if(line.startsWith("[SECCIÓN ESPECIAL FWC]")){section="fwc";return}if(line.startsWith("[SECCIÓN ESPECIAL COCA")){section="cc";return}if(line.startsWith("País;")||line.startsWith("Número de Lámina;"))return;const p=line.split(";");if(section==="teams"&&p.length>=4){const[country,code,number,...nameParts]=p;data.teams[code]??={};data.teams[code][number]={country,code,number,name:nameParts.join(";")}}if(section==="fwc"&&p.length>=2){const[number,...nameParts]=p;data.fwc[number]={number,name:nameParts.join(";")}}if(section==="cc"&&p.length>=4){const[country,code,number,...nameParts]=p;data.cc[number]={country,code,number,name:nameParts.join(";")}}});return data}
async function loadOfficialDataFromRepo(){updateOfficialStatus();try{const response=await fetch("album-data.txt?v=7",{cache:"no-store"});if(!response.ok)throw new Error("No se pudo leer album-data.txt");const text=await response.text(),parsed=parseStickerText(text),total=Object.values(parsed.teams).reduce((sum,t)=>sum+Object.keys(t).length,0)+Object.keys(parsed.fwc).length+Object.keys(parsed.cc).length;if(!total)throw new Error("album-data.txt no contiene datos válidos");stickerData=parsed;officialDataLoaded=true;saveStickerData();render()}catch(e){console.warn(e);const fallback=countStickerRows();officialDataLoaded=fallback>0;$("#officialDataStatus").textContent=fallback?`Base oficial cargada desde respaldo local: ${fallback} láminas.`:"No se pudo cargar la base oficial de láminas."}}
function loadUiScale(){try{const v=Number(localStorage.getItem(UI_SCALE_KEY));return Number.isFinite(v)?Math.min(1.2,Math.max(.78,v)):1}catch{return 1}}function applyUiScale(){document.documentElement.style.setProperty("--page-scale",uiScale.toFixed(2));$("#uiScaleText").textContent=`${Math.round(uiScale*100)}%`;document.body.classList.toggle("view-compact",uiScale<=.92&&uiScale>.82);document.body.classList.toggle("view-ultra",uiScale<=.82);document.body.classList.toggle("view-large",uiScale>=1.08);localStorage.setItem(UI_SCALE_KEY,String(uiScale))}function toggleUiScaleMenu(){$("#uiScaleControl").classList.toggle("open")}function changeUiScale(delta){uiScale=Math.min(1.2,Math.max(.78,Math.round((uiScale+delta)*100)/100));applyUiScale()}function resetUiScale(){uiScale=1;applyUiScale()}function scrollToSection(id){document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"})}function setupStatLinks(){document.querySelectorAll("[data-scroll]").forEach(e=>e.addEventListener("click",()=>scrollToSection(e.dataset.scroll)))}function setupModalClose(){$("#cardModal").addEventListener("click",e=>{if(e.target.id==="cardModal")closeCardModal()})}
function loadScriptOnce(src){return new Promise((resolve,reject)=>{if(document.querySelector(`script[src="${src}"]`)){resolve();return}const script=document.createElement("script");script.src=src;script.async=true;script.onload=resolve;script.onerror=()=>reject(new Error(`No se pudo cargar ${src}`));document.head.appendChild(script)})}
async function ensurePdfLibraries(){if(window.jspdf?.jsPDF&&window.jspdf.jsPDF.API?.autoTable)return;if(!pdfLibrariesLoading)pdfLibrariesLoading=(async()=>{await loadScriptOnce("https://cdn.jsdelivr.net/npm/jspdf@2.5.1/dist/jspdf.umd.min.js");await loadScriptOnce("https://cdn.jsdelivr.net/npm/jspdf-autotable@3.8.4/dist/jspdf.plugin.autotable.min.js")})();await pdfLibrariesLoading;if(!window.jspdf?.jsPDF)throw new Error("jsPDF no quedó disponible.")}
async function ensureOfficialDataForExport(){if(!officialDataLoaded)await loadOfficialDataFromRepo()}
function getTodayText(){return new Date().toLocaleString("es-CL",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"})}function getSafeDateForFile(){return new Date().toISOString().slice(0,10)}
function getPdfExportRows(type){const rows=[];album.forEach(section=>section.countries.forEach(country=>{const collection={section,country};getRowsForCollection(collection,type).forEach(row=>rows.push({group:section.title,country:country.display,code:row.meta.code,number:row.meta.number,name:row.meta.name,duplicates:row.entry.duplicates||0}))}));return rows}
async function getLogoDataUrl(){try{const response=await fetch("assets/img/mundial_2026.png?v=1",{cache:"force-cache"});if(!response.ok)return null;const blob=await response.blob();return await new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>resolve(null);reader.readAsDataURL(blob)})}catch{return null}}
function drawPdfHeader(doc,title,subtitle,logo){const w=doc.internal.pageSize.getWidth();doc.setFillColor(7,17,31);doc.rect(0,0,w,34,"F");doc.setFillColor(53,194,255);doc.rect(0,33.2,w,.8,"F");if(logo){try{doc.addImage(logo,"PNG",w-28,6,18,18)}catch{}}doc.setFont("helvetica","bold");doc.setFontSize(17);doc.setTextColor(255,255,255);doc.text(title,12,14);doc.setFont("helvetica","normal");doc.setFontSize(9);doc.setTextColor(185,204,230);doc.text(subtitle,12,22)}
function drawPdfFooter(doc){const n=doc.internal.getNumberOfPages(),w=doc.internal.pageSize.getWidth(),h=doc.internal.pageSize.getHeight();for(let p=1;p<=n;p++){doc.setPage(p);doc.setFont("helvetica","normal");doc.setFontSize(8);doc.setTextColor(120,135,160);doc.text("Álbum FIFA 2026 · Control personal de láminas",12,h-8);doc.text(`Página ${p} de ${n}`,w-12,h-8,{align:"right"})}}

function makePdfTableBody(rows,type){return rows.map(r=>{const base=[r.group,r.country,r.code,r.number,r.name];if(type==="duplicate")base.push(String(r.duplicates));return base})}
async function exportPdf(type){try{await ensureOfficialDataForExport();await ensurePdfLibraries();const{jsPDF}=window.jspdf,doc=new jsPDF({orientation:"portrait",unit:"mm",format:"a4"}),rows=getPdfExportRows(type),logo=await getLogoDataUrl(),isMissing=type==="missing",title=isMissing?"Cartas faltantes · Álbum FIFA 2026":"Cartas repetidas · Álbum FIFA 2026",subtitle=isMissing?"Listado para compartir: láminas que me faltan por encontrar.":"Listado para compartir: láminas repetidas disponibles para intercambio.";drawPdfHeader(doc,title,subtitle,logo);if(!rows.length){const y=52;doc.setFont("helvetica","bold");doc.setFontSize(13);doc.setTextColor(7,17,31);doc.text(isMissing?"No tienes cartas faltantes registradas.":"No tienes cartas repetidas registradas.",12,y)}else{const head=isMissing?[["Grupo","País / sección","Código","N°","Lámina"]]:[["Grupo","País / sección","Código","N°","Lámina","Cant."]];doc.autoTable({startY:42,head,body:makePdfTableBody(rows,type),theme:"grid",margin:{left:12,right:12,top:42,bottom:16},styles:{font:"helvetica",fontSize:8,cellPadding:2,lineColor:[218,226,238],lineWidth:.15,overflow:"linebreak",valign:"middle"},headStyles:{fillColor:isMissing?[53,95,140]:[150,112,32],textColor:[255,255,255],fontStyle:"bold"},alternateRowStyles:{fillColor:[246,248,252]},columnStyles:isMissing?{0:{cellWidth:22},1:{cellWidth:36},2:{cellWidth:18},3:{cellWidth:18},4:{cellWidth:"auto"}}:{0:{cellWidth:22},1:{cellWidth:35},2:{cellWidth:18},3:{cellWidth:18},4:{cellWidth:"auto"},5:{cellWidth:14,halign:"center",fontStyle:"bold"}},didDrawPage:()=>drawPdfHeader(doc,title,subtitle,logo)})}drawPdfFooter(doc);doc.save(isMissing?`album-fifa-2026-faltantes-${getSafeDateForFile()}.pdf`:`album-fifa-2026-repetidas-${getSafeDateForFile()}.pdf`)}catch(e){console.error(e);alert("No se pudo generar el PDF. Revisa tu conexión a internet, porque la exportación usa la librería jsPDF desde CDN.")}}
function exportMissingPdf(){exportPdf("missing")}function exportDuplicatesPdf(){exportPdf("duplicate")}
function render(){renderTabs();renderContent();updateStats();renderFilters();renderMovementLog();updateOfficialStatus();applyUiScale()}
if(IS_BROWSER){setupFilterListeners();setupStatLinks();setupModalClose();render();loadOfficialDataFromRepo();initFirebase()}else globalThis.__albumTestApi={formatDateTimeParts,createMovementEntry,getDashboardMetrics};
